import type { Metadata } from 'next'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { env } from '@/config/env'
import { ApiResponse } from '@/types/api/api-response'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface AuthUserData {
  id: number
  email: string
  firstName: string
  lastName: string
  role: {
    id: number
    name: string
  }
  createdAt: string
  updatedAt: string
}

export default async function TalentLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const token = cookies().get(env.AUTH_COOKIE_NAME)?.value

  if (!token) {
    redirect('/auth/login')
  }

  async function getAuthenticatedUser(
    token: string,
  ): Promise<ApiResponse<AuthUserData>> {
    try {
      const res = await fetch(`${env.SERVER_URL}/auth/me/`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })

      if (res.status === 401) {
        redirect('/auth/login')
      }

      return res.json()
    } catch (err) {
      redirect('/error/500')
    }
  }

  const authData = await getAuthenticatedUser(token)
  const user = authData.data
  const userInitials =
    user.firstName[0].toUpperCase() + user.lastName[0].toUpperCase()

  if (!user) {
    redirect('/error/500')
  }

  return (
    <div className='px-16 py-8'>
      <div className='fixed right-8 top-6 z-50'>
        <DropdownMenu>
          <DropdownMenuTrigger>
            <Avatar>
              <AvatarImage src='' />
              <AvatarFallback className='font-semibold text-primary'>
                {userInitials}
              </AvatarFallback>
            </Avatar>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuLabel>My Account</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Profile</DropdownMenuItem>
            <DropdownMenuItem>Billing</DropdownMenuItem>
            <DropdownMenuItem>Team</DropdownMenuItem>
            <DropdownMenuItem>Subscription</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
      {children}
    </div>
  )
}
